kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: website-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: my-website
    spec:
      containers:
      - name: nginx
        image: eu.gcr.io/clevmindblog/website:2
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        -  containerPort: 80
